baseURL: "https://junyangqi.com/" 
title: Junyang Qi, PhD
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Featured Publications
          url: papers/
          weight: 1
        - name: Posts
          url: posts/
          weight: 2
        - name: Curriculum Vitae
          url: CV - Junyang Qi.pdf
          weight: 3
        - name: LinkedIn
          url: https://linkedin.com/in/junyangqi/
          weight: 4
        - name: UCSF Profiles
          url: https://profiles.ucsf.edu/junyang.qi/
          weight: 5
        - name: Michael Evans' Lab
          url: https://radiology.ucsf.edu/research/labs/evans
          weight: 6
params:
  description: "This website hosts Dr. Junyang Qi's research, curriculum vitae, and contact information."
  author: Name
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
          enabled: true
          title: Junyang Qi
          subtitle: "Hi there! I'm Junyang, a postdoctoral researcher in the Radiology and Biomedical Imaging Department at the University of California, San Francisco, working with [<u>Prof. Michael Evans</u>](https://radiology.ucsf.edu/people/michael-evans/).

          <br><br>
          My research focuses on developing small-molecules, peptides, nanomedicines, and radioligands for cancer theranostics. I have extensive experience in establishing in vivo cancer models to support and develop cancer imaging (e.g., NIRF, PA, PET, SPECT) and therapeutic strategies (e.g., chemotherapy, phototherapy, radiotherapy).  

          <br><br>
          I earned my PhD in medicinal chemistry from Sun Yat-sen University in 2021 under the supervision of Prof. Wenbin Deng, followed by two years of postdoctoral training. In 2024, I joined the Evans Lab at UCSF to expand my work into radiotherapeutics, focusing on the development of radiolabeled ligands and probes for precision cancer theranostics."
          imageUrl: "ac photo sq.jpg"
          imageWidth: 160   
          imageHeight: 160
          buttons:
            - name: Featured Publications
              url: papers/
            - name: News
              url: Posts/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: CV
              url: CV - Junyang Qi.pdf
            - name: UCSF Profiles
              url: https://profiles.ucsf.edu/junyang.qi/
            #- name: Archive
            #  url: archive/
  socialIcons:
        - name: Email
          url: mailto:junyang.qi@ucsf.edu
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=GwDnwrwAAAAJ&hl=en/
        - name: LinkedIn
          url: https://linkedin.com/in/junyangqi/
        - name: ORCID
          url: https://orcid.org/0009-0008-8275-4426/

  assets:
        disableHLJS: true
        disableScrollBarStyle: true
  cover:
        hiddenInList: false
        hiddenInSingle: true
  label:
      text: "Junyang Qi, PhD"
      icon: favicon.ico
      iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
